FROM nginx:1.15
# Per default nginx document root is /usr/share/nginx/html 
COPY index.html /usr/share/nginx/html
# Per default nginx already contains a CMD in its image so we don't need anything else here.