
package com.jesperdj.jaxb.domain;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PurchaseOrders", targetNamespace = "http://www.jesperdj.com/ps-jaxb")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PurchaseOrders {


    /**
     * 
     * @param id
     * @return
     *     returns com.jesperdj.jaxb.domain.PurchaseOrder
     */
    @WebMethod
    @WebResult(name = "order", targetNamespace = "")
    @RequestWrapper(localName = "getOrder", targetNamespace = "http://www.jesperdj.com/ps-jaxb", className = "com.jesperdj.jaxb.domain.GetOrder")
    @ResponseWrapper(localName = "getOrderResponse", targetNamespace = "http://www.jesperdj.com/ps-jaxb", className = "com.jesperdj.jaxb.domain.GetOrderResponse")
    @Action(input = "http://www.jesperdj.com/ps-jaxb/PurchaseOrders/getOrderRequest", output = "http://www.jesperdj.com/ps-jaxb/PurchaseOrders/getOrderResponse")
    public PurchaseOrder getOrder(
        @WebParam(name = "id", targetNamespace = "")
        long id);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "deleteOrder", targetNamespace = "http://www.jesperdj.com/ps-jaxb", className = "com.jesperdj.jaxb.domain.DeleteOrder")
    @ResponseWrapper(localName = "deleteOrderResponse", targetNamespace = "http://www.jesperdj.com/ps-jaxb", className = "com.jesperdj.jaxb.domain.DeleteOrderResponse")
    @Action(input = "http://www.jesperdj.com/ps-jaxb/PurchaseOrders/deleteOrderRequest", output = "http://www.jesperdj.com/ps-jaxb/PurchaseOrders/deleteOrderResponse")
    public void deleteOrder(
        @WebParam(name = "id", targetNamespace = "")
        long id);

    /**
     * 
     * @return
     *     returns java.util.List<com.jesperdj.jaxb.domain.PurchaseOrder>
     */
    @WebMethod
    @WebResult(name = "orders", targetNamespace = "")
    @RequestWrapper(localName = "getOrders", targetNamespace = "http://www.jesperdj.com/ps-jaxb", className = "com.jesperdj.jaxb.domain.GetOrders")
    @ResponseWrapper(localName = "getOrdersResponse", targetNamespace = "http://www.jesperdj.com/ps-jaxb", className = "com.jesperdj.jaxb.domain.GetOrdersResponse")
    @Action(input = "http://www.jesperdj.com/ps-jaxb/PurchaseOrders/getOrdersRequest", output = "http://www.jesperdj.com/ps-jaxb/PurchaseOrders/getOrdersResponse")
    public List<PurchaseOrder> getOrders();

    /**
     * 
     * @param order
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "id", targetNamespace = "")
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://www.jesperdj.com/ps-jaxb", className = "com.jesperdj.jaxb.domain.AddOrder")
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://www.jesperdj.com/ps-jaxb", className = "com.jesperdj.jaxb.domain.AddOrderResponse")
    @Action(input = "http://www.jesperdj.com/ps-jaxb/PurchaseOrders/addOrderRequest", output = "http://www.jesperdj.com/ps-jaxb/PurchaseOrders/addOrderResponse")
    public long addOrder(
        @WebParam(name = "order", targetNamespace = "")
        PurchaseOrder order);

}
