//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.14 at 08:32:07 PM CEST 
//


package com.jesperdj.jaxb.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for loyalty.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="loyalty">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *     &lt;enumeration value="10"/>
 *     &lt;enumeration value="20"/>
 *     &lt;enumeration value="30"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "loyalty")
@XmlEnum(Integer.class)
public enum Loyalty {

    @XmlEnumValue("10")
    BRONZE(10),
    @XmlEnumValue("20")
    SILVER(20),
    @XmlEnumValue("30")
    GOLD(30);
    private final int value;

    Loyalty(int v) {
        value = v;
    }

    public int value() {
        return value;
    }

    public static Loyalty fromValue(int v) {
        for (Loyalty c: Loyalty.values()) {
            if (c.value == v) {
                return c;
            }
        }
        throw new IllegalArgumentException(String.valueOf(v));
    }

}
